disabled = false
languageCode = "ko"
languageName = "Korean"
weight = 1
title = "skeep.cat"

[params]
  displayName = "KO"
  isoCode = "ko"
  rtl = false
  dateFormat = "2 January 2006"
  # logo = "img/logo.png"
  # secondaryLogo = "img/secondary-logo.png"
  description = "personal blog to post software development skill and introduce to catalonia"
  copyright = "© 2025 skeep194"

[params.author]
  name = "skeep194"
  email = "me@skeep.cat"
  image = "img/main.jpg"
  imageQuality = 96
  headline = "개발향 첨가 일상을 맛봐요.\n\n.cat 도메인에 대해 궁금하면 [**여기**](https://skeep.cat)를 눌러주세요!"
  bio = "어쩌다 개발자"
  links = [
    { email = "mailto:me@skeep.cat" },
    { link = "https://codeforces.com/profile/skeep194" },
    # { amazon = "https://www.amazon.com/hz/wishlist/ls/wishlist-id" },
    # { apple = "https://www.apple.com" },
    # { blogger = "https://username.blogspot.com/" },
    # { bluesky = "https://bsky.app/profile/username" },
    # { codepen = "https://codepen.io/username" },
    # { dev = "https://dev.to/username" },
    # { discord = "https://discord.gg/invitecode" },
    # { dribbble = "https://dribbble.com/username" },
    # { facebook = "https://facebook.com/username" },
    # { flickr = "https://www.flickr.com/photos/username/" },
    # { foursquare = "https://foursquare.com/username" },
    { github = "https://github.com/skeep194" },
    # { gitlab = "https://gitlab.com/username" },
    # { google = "https://www.google.com/" },
    # { hashnode = "https://username.hashnode.dev" },
    { instagram = "https://instagram.com/skeep194" },
    # { itch-io = "https://username.itch.io" },
    # { keybase = "https://keybase.io/username" },
    # { kickstarter = "https://www.kickstarter.com/profile/username" },
    # { lastfm = "https://lastfm.com/user/username" },
    # { linkedin = "https://linkedin.com/in/username" },
    # { mastodon = "https://mastodon.instance/@username" },
    # { medium = "https://medium.com/username" },
    # { microsoft = "https://www.microsoft.com/" },
    # { orcid = "https://orcid.org/userid" },
    # { patreon = "https://www.patreon.com/username" },
    # { pinterest = "https://pinterest.com/username" },
    # { reddit = "https://reddit.com/user/username" },
    # { researchgate = "https://www.researchgate.net/profile/username" },
    # { slack = "https://workspace.url/team/userid" },
    # { snapchat = "https://snapchat.com/add/username" },
    # { soundcloud = "https://soundcloud.com/username" },
    # { spotify = "https://open.spotify.com/user/userid" },
    # { stack-overflow = "https://stackoverflow.com/users/userid/username" },
    { steam = "https://steamcommunity.com/profiles/76561198202573884" },
    # { telegram = "https://t.me/username" },
    # { threads = "https://www.threads.net/@username" },
    # { tiktok = "https://tiktok.com/@username" },
    # { tumblr = "https://username.tumblr.com" },
    # { twitch = "https://twitch.tv/username" },
    # { twitter = "https://twitter.com/username" },
    # { x-twitter = "https://twitter.com/username" },
    # { whatsapp = "https://wa.me/phone-number" },
    # { youtube = "https://youtube.com/username" },
    # { ko-fi = "https://ko-fi.com/username" },
    # { codeberg = "https://codeberg.org/username"},
  ]
